import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { EntityRelationalHelper } from '../../utils/relational-entity-helper';
import { CurrencyEnum, PrStatusEnum } from '../../common/enums';
import { numericTransformer } from '../../utils/transformers/numeric.transformer';
import { DepartmentEntity } from '../../org/entities/department.entity';
import { ProjectEntity } from '../../org/entities/project.entity';
import { UserEntity } from '../../users/infrastructure/persistence/relational/entities/user.entity';
import { PurchaseRequestItemEntity } from './purchase-request-item.entity';

@Entity({ name: 'purchase_requests' })
export class PurchaseRequestEntity extends EntityRelationalHelper {
  @PrimaryGeneratedColumn()
  id: number;

  // defaulted in the DB: 'PR-' || lpad(nextval('pr_number_seq'), 4, '0')
  @Column({ name: 'pr_number', type: 'text' })
  prNumber: string;

  @Index('purchase_requests_requester_idx')
  @ManyToOne(() => UserEntity)
  @JoinColumn({ name: 'requester_id' })
  requester: UserEntity;

  @Index('purchase_requests_status_idx')
  @Column({
    name: 'status',
    type: 'enum',
    enum: PrStatusEnum,
    enumName: 'pr_status',
    default: PrStatusEnum.draft,
  })
  status: PrStatusEnum;

  @Column({
    name: 'currency',
    type: 'enum',
    enum: CurrencyEnum,
    enumName: 'currency',
    default: CurrencyEnum.USD,
  })
  currency: CurrencyEnum;

  // locked at submit; units per 1 USD
  @Column({
    name: 'exchange_rate',
    type: 'numeric',
    precision: 18,
    scale: 6,
    default: 1,
    transformer: numericTransformer,
  })
  exchangeRate: string;

  @Column({
    name: 'total_original',
    type: 'numeric',
    precision: 18,
    scale: 4,
    default: 0,
    transformer: numericTransformer,
  })
  totalOriginal: string;

  // derived by trigger T1 — never write this directly
  @Column({
    name: 'total_usd',
    type: 'numeric',
    precision: 18,
    scale: 4,
    default: 0,
    transformer: numericTransformer,
  })
  totalUsd: string;

  @ManyToOne(() => DepartmentEntity, { nullable: true })
  @JoinColumn({ name: 'department_id' })
  department: DepartmentEntity | null;

  @ManyToOne(() => ProjectEntity, { nullable: true })
  @JoinColumn({ name: 'project_id' })
  project: ProjectEntity | null;

  @Column({ name: 'note', type: 'text', nullable: true })
  note: string | null;

  @ManyToOne(() => UserEntity, { nullable: true })
  @JoinColumn({ name: 'approver_id' })
  approver: UserEntity | null;

  @Column({ name: 'decided_at', type: 'timestamptz', nullable: true })
  decidedAt: Date | null;

  @Column({ name: 'telegram_message_id', type: 'bigint', nullable: true })
  telegramMessageId: string | null;

  @Column({ name: 'telegram_chat_id', type: 'bigint', nullable: true })
  telegramChatId: string | null;

  @Column({ name: 'auto_generated', type: 'boolean', default: false })
  autoGenerated: boolean;

  @OneToMany(() => PurchaseRequestItemEntity, (item) => item.purchaseRequest)
  items: PurchaseRequestItemEntity[];

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;
}
